name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install LaTeX
      run: sudo apt-get install -y texlive-latex-base texlive-latex-extra
    - name: Make CV PDF
      run: make -C cv
